FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["gozon.apigateway/gozon.apigateway.csproj", "gozon.apigateway/"]

RUN dotnet restore "gozon.apigateway/gozon.apigateway.csproj"

COPY . .
WORKDIR "/src/gozon.apigateway"

RUN dotnet build "gozon.apigateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "gozon.apigateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "gozon.apigateway.dll"]